source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.6'
# Use postgresql as the database for Active Record
gem 'pg'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
gem 'rails_12factor'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jquery-turbolinks'
gem 'devise'
gem 'nested_form'
gem 'exception_notification'

gem 'carrierwave'
gem 'rmagick'
gem 'kaminari'
gem 'bootstrap-kaminari-views'
gem 'fog'
gem 'puma'

gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
group :development do
  gem 'chrome_logger' , require: 'chrome_logger/railtie'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem "quiet_assets", ">= 1.0.1"
  gem 'better_errors'
  gem 'xray-rails'
  gem 'rack-mini-profiler', require: false
  gem 'bullet'
  gem 'awesome_print'
  gem "letter_opener"
  gem 'faker'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-nav'
  gem 'pry-doc'
  gem 'pry-stack_explorer'
  gem 'pry-rescue'
end


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

